export const darkTheme = {
  colors: {
    "base-white": "#000000",
    "base-background": "#0F0F0F",
    "base-card": "#000",
    "base-input": "#000",
    "base-button": "#adb5bd",
    "base-hover": "#212529",
    "base-label": "#F3F2F2",
    "base-text": "#F3F2F2",
    "base-subtitle": "#F3F2F2",
    "base-title": "#4B2995",
    "base-error": "#f84747",

    "brand-purple-dark": "#4B2995",
    "brand-purple": "#8047F8",
    "brand-purple-light": "#0F0F0F",
    "brand-yellow-dark": "#C47F17",
    "brand-yellow": "#DBAC2C",
    "brand-yellow-light": "#F1E9C9",
  },
  textSizes: {
    "title-title-xl": "3rem",
    "title-title-l": "2rem",
    "title-title-m": "1.5rem",
    "title-title-s": "1.2rem",
    "title-title-xs": "1.125rem",
    "text-regular-l": "1.25rem",
    "text-bold-l": "1.25rem",
    "text-regular-m": "1rem",
    "text-bold-m": "1rem",
    "text-regular-s": "0.875rem",
    "text-bold-s": "0.75rem",
    "components-tag": "0.625rem",
    "components-button-g": "0.875rem",
    "components-button-s": "0.75rem",
  },
  fonts: {
    regular: "'Roboto'",
    title: "'Baloo 2'",
  },
};